openapi: 3.0.3
info:
  title: JEE Webshop API
  description: |
    Allows connected authorized systems to add or update articles in the webshop

  version: 0.1.0
  x-audience: business-software-internal

tags:
  - name: article
    description: Article routes
  - name: article image
    description: Article image routes
  - name: category
    description: Category routes
  - name: subcategory
    description: Subcategory routes

paths:
  /api/add-article:
    post:
      summary: Create a new article
      tags:
        - article
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/article'
      responses:
        201:
          description: The article has been created
        400:
          description: |
            Unable to create article.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/update-article:
    post:
      summary: Update an article
      tags:
        - article
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/article'
      responses:
        200:
          description: The article has been updated
        400:
          description: |
            Unable to update article.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/delete-article/{sku}:
    delete:
      summary: Delete an article
      tags:
        - article
      parameters:
        - $ref: '#/components/parameters/sku'
      responses:
        200:
          description: The article has been deleted
        400:
          description: |
            Unable to delete article.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/add-article-image:
    post:
      summary: Create a new article image
      tags:
        - article image
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/articleImage'
      responses:
        201:
          description: The article image has been created
        400:
          description: |
            Unable to create article image.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/update-article-image:
    post:
      summary: Update an article image
      tags:
        - article image
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/articleImage'
      responses:
        200:
          description: The article image has been updated
        400:
          description: |
            Unable to update article image.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/delete-article-image/{uuid}:
    delete:
      summary: Delete an article image
      tags:
        - article image
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        200:
          description: The article image has been deleted
        400:
          description: |
            Unable to delete article image.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/add-category:
    post:
      summary: Create a new category
      tags:
        - category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/category'
      responses:
        201:
          description: The category has been created
        400:
          description: |
            Unable to create category.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/update-category:
    post:
      summary: Update an category
      tags:
        - category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/category'
      responses:
        200:
          description: The category has been updated
        400:
          description: |
            Unable to update category.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/delete-category/{uuid}:
    delete:
      summary: Delete an category
      tags:
        - category
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        200:
          description: The category has been deleted
        400:
          description: |
            Unable to delete category.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized  

  /api/add-subcategory:
    post:
      summary: Create a new subcategory
      tags:
        - subcategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subcategory'
      responses:
        201:
          description: The subcategory has been created
        400:
          description: |
            Unable to create subcategory.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/update-subcategory:
    post:
      summary: Update an subcategory
      tags:
        - subcategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subcategory'
      responses:
        200:
          description: The subcategory has been updated
        400:
          description: |
            Unable to update subcategory.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized

  /api/delete-subcategory/{uuid}:
    delete:
      summary: Delete a subcategory
      tags:
        - subcategory
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        200:
          description: The subcategory has been deleted
        400:
          description: |
            Unable to delete subcategory.
            Most likely indicating that the request missed required parameters.
        401:
          description: |
            Unauthorized          


  # endregion

components:
  schemas:

    # region models
    # -------------
    article:
      description: Article model
      type: object
      properties:
        sku:
          $ref: '#/components/schemas/sku'
        title:
          $ref: '#/components/schemas/title'
        description:
          $ref: '#/components/schemas/description'
        sellingPrice:
          $ref: '#/components/schemas/sellingPrice'
        listPrice:
          $ref: '#/components/schemas/listPrice'
        available:
          $ref: '#/components/schemas/available'
        stock:
          $ref: '#/components/schemas/stock'
        subcategory:
          $ref: '#/components/schemas/subcategory'
        imageList:
          $ref: '#/components/schemas/imageList'

    subcategory:
      description: Subcategory
      type: object
      properties:
        uuid:
          $ref: '#/components/schemas/uuid'
        categoryName:
          $ref: '#/components/schemas/title'
        rootCategoryUuid:
          $ref: '#/components/schemas/uuid'
        rootCategory:
          $ref: '#/components/schemas/category'

    category:
      description: Category
      type: object
      properties:
        uuid:
          $ref: '#/components/schemas/uuid'
        categoryName:
          $ref: '#/components/schemas/title'

    articleImage:
      description: Article image
      type: object
      properties:
        uuid:
          $ref: '#/components/schemas/uuid'
        articleSku:
          $ref: '#/components/schemas/sku'
        imageURL:
          $ref: '#/components/schemas/url'
        position:
          $ref: '#/components/schemas/index'

    # ---------
    # endregion

    # region properties
    # -----------------
    uuid:
      type: string
      description: 36-character hexidecimal string of the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      maximum: 36
      example: 008bf81b-5a1a-4d8d-b147-0508475a31cf

    sku:
      type: number
      description: article number
      maximum: 9223372036854775807
      example: 12345

    link:
      type: string
      description: web link string of the format https://www.xxxxxxx.xxx/....
      maximum: 2048
      example: https://www.mydomain.xyz/image/123456

    title:
      type: string
      description: title / name
      maximum: 255
      example: "Blue T-Shirt Size M"

    description:
      type: string
      description: descriptive text
      maximum: 65535
      example: "This blue t-shirt gives you a classic look"

    sellingPrice:
      type: number
      description: current price of the article incl. possible discounts
      maximum: 1.79769313486231570e308
      example: 25.99

    listPrice:
      type: number
      description: original price of article - without discounts etc.
      maximum: 1.79769313486231570e308
      example: 39.99

    available:
      type: boolean
      description: is the article currently purchasable
      example: true

    stock:
      type: number
      description: available amount of the article
      maximum: 2147483647
      example: 150

    url:
      type: number
      description: web link
      maximum: 2048
      example: https://www.mydomain.xyz/image/12345

    index:
      type: number
      description: number indicating a position
      maximum: 2147483647
      example: 5

    imageList:
      type: array
      items:
        type: object
        oneOf:
          - $ref: '#/components/schemas/articleImage'

  parameters:
    sku:
      name: sku
      description: article sku
      in: path
      required: true
      schema:
        type: number
        maximum: 9223372036854775807
      example: 12345

    uuid:
      name: uuid
      description: 36-character hexidecimal string of the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      in: path
      required: true
      schema:
        type: string
        maximum: 36
      example: 008bf81b-5a1a-4d8d-b147-0508475a31cf
  requestBodies:
    article:
      description: Article object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/article'
  