name: Render documentation
on: [ push ]


permissions:
  contents: read
  pages: write
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: arc42/documentation.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: ARC42 Documentation
          path: arc42/arc42_documentation.pdf
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: main
          commit_options: '--no-verify --signoff'
          commit_author: Author <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true
  render-swagger:
    runs-on: ubuntu-latest
    environment: no-rule
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger/documentation.json

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: swagger-ui

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4